// <auto-generated />
namespace StudSigns.Migrations.StudentMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UserInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserInit));
        
        string IMigrationMetadata.Id
        {
            get { return "202010082234501_UserInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
