// <auto-generated />
namespace StudSigns.Migrations.StudentMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OnlyDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OnlyDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202010221016180_OnlyDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
